apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: vinishasvijayakumar/task-ease-backend:latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://dpg-cusopl5svqrc73dvfntg-a:5432/hospital_system_li0r"
            - name: SPRING_DATASOURCE_USERNAME
              value: "hospital_system"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "RklPD9dyENasx0JVbJWjWl8zEzzgPfV3"
            - name: SPRING_JWT_SECRET
              value: "C22134503B503CE38256C0B1919ACEABACADCE3F6169C11D228894BCF0B2BF72"
          ports:
            - containerPort: 8080
