apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: vinishasvijayakumar/taskmanagementsystem:latest
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              value: hospital_system
            - name: SPRING_DATASOURCE_PASSWORD
              value: RklPD9dyENasx0JVbJWjWl8zEzzgPfV3
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort  # Change to LoadBalancer for cloud deployment
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007  # Only for NodePort
  selector:
    app: backend
