apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: vinishasvijayakumar/taskmanagementsystem:latest
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres  # ✅ Updated username
            - name: SPRING_DATASOURCE_PASSWORD
              value: vinisha@97  # ✅ Updated password
          ports:
            - containerPort: 8080
